#!/bin/env bash


### =========
### Variables
### =========

# A directory where the backups will be placed.
backup_dir=

# The command that will return a byte stream of data to back up on stdout.
# Usually this will be tar or ssh or rsync.
# Output has to be stream on stdout
source_command=

# Alternative to source command: path to a local source file
# that will be copied
source_file=

# Filename of the backup
backup_name=

# How many backups shold be kept.
keep_count=

# Suffix that will be appended to fhe filename after timestamp
name_suffix=

# Is set, if the new file name should be the same as the old one.
preserve_name=

help_string="$0 (-x COMMAND | -c PATH) [OPTIONS] BACKUP_DIRECTORY KEEP_COUNT
 Description:
    Creates a backup of file or data stream and saves it toa a given BACKUP_DIRECTORY.
    Then it will check if BACKUP_DIRECTORY contains more backups than KEEP_COUNT and
    if so, deletes the oldest ones, based on the time-stamp in their file name.
 Positional arguments:
    BACKUP_DIRECTORY:  Location of the directory containing the backups.
    KEEP_COUNT:        The number of the most recent backups that should be kept.
 Compulsory options (one of these options has to be specified):
    -x COMMAND: Specify a command which will return data you want to backup
                on stdout.
    -c PATH:    Specify a path to a file you want to backup. If a path to a directory
                was given, the program will pick the (alphabetically) first file
                in this directory. The program will attempt to create a backup
                using a hardlink. If it's not possible, then the file will be
                copied.
 Options:
    -h:         Display this message
    -N:         Keep old filename. This can be used only when using the '-c' option.
    -n NAME:    Sets the name of the backup file to a give string. NOTE: This
                program only cleans up old files that begin their name with a time-stamp,
                so your name should follow the 'date -uIseconds' format.
    -s SUFFIX:  Sets a suffix that will be added to the end of the newly created file.
                Usually you will want to use this option for adding a file extension "


### ====================
### Processing arguments
### ====================
while getopts 'hn:Ns:x:c:' o; do
    case "$o" in
        # Print help
        h)
            echo "$help_string"
            exit 0
            ;;

        # Execute to get backup
        n)
            n=$(( $OPTIND - 1 ))
            backup_name=${!n}
            ;;
        # Keep original filename
        N)
            if [ -z "$source_file" ]; then
                echo "You have to specify a source file (-c) before -N!"
                exit 1
                fi
            backup_name=$(echo "$source_file" | awk -F "/" '{print $(NF)}')
            preserve_name=1
            ;;
        # Set suffix
        s)
            n=$(( $OPTIND - 1 ))
            name_suffix=${!n}
            ;;
        # Backup with command
        x)
            n=$(( $OPTIND - 1 ))
            source_command=${!n}
            ;;
        # Backup by copy
        c)
            n=$(( $OPTIND - 1 ))
            source_file=${!n}
            ;;
        *)
            echo "Use '$0 -h' for help"
            exit 1
            ;;
    esac
done

# Edgecases
if [[ "$source_command" && "$source_file" ]]; then
    echo "Both source file '-c' and source command '-x' have been given! Pick one!"
    exit 1
    fi

if [[ ! ("$source_command" || "$source_file") ]]; then
    echo "You either have to specify source command '-x' or a source file '-c'"
    exit 1
    fi

# Shifting arguments to account for flags.
shift $(($OPTIND -1))

backup_dir="$1"
# Add trailing slash if it's not there already.
if [ -z $(echo "$backup_dir" | grep -E ".*/$") ]; then
    backup_dir="$backup_dir/"
    fi

keep_count="$2"

if [ "$#" -ne 2 ]; then
    echo "Bad arguments!" >/dev/stderr
    exit 1
    fi

### ====================
### Create the backup up
### ====================
# Generate backup name
if [ -z "$backup_name" ]; then
    backup_name="$(date -uIseconds)"
    fi

# Execute backup
if [ "$source_command" ]; then
(echo "$source_command" | sh > "${backup_dir}/${backup_name}""${name_suffix}") \
    || (echo "Error creating backup!" > /dev/stderr; exit 1)

else
    if [ -d "$source_file" ]; then
        # Add trailing "/" if its missing
        if [ -z $(echo "$source_file" | grep -E ".*/$") ]; then
            source_file="$source_file/"
            fi
        echo "$source_file"
        source_file="${source_file}""$(ls "$source_file" | sort | sed 1q)"
        echo "$source_file"

        if [ -z "$source_file" ]; then
            echo "Source directory seem to be empty" >/dev/stderr
            exit 1
            fi

        if [ "$preserve_name" ]; then
            echo "testdjalskfjdsklj"
            backup_name=$(echo "$source_file" | awk -F "/" '{print $(NF)}')
            fi

        fi

    # Try to hardlink, else just copy sourcefile to backup dir.
    (ln "$source_file" "${backup_dir}/${backup_name}""${name_suffix}" \
        || cp "$source_file" "${backup_dir}/${backup_name}""${name_suffix}") \
        || (echo "Error creating backup!" > /dev/stderr; exit 1)
    fi

### ==================
### Delete old backups
### ==================
delete_list=$(ls "${backup_dir}" | grep -E "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*" | sort -r | awk -F "\n" -v keep=${keep_count} -v dir=${backup_dir} '
                 BEGIN{
                    cnt=0
                 } {
                    if (cnt >= keep)
                        {printf "\"" dir $0 "\" "}
                        cnt++
                 }')

if [ "$delete_list" ]; then
    echo ${delete_list} | xargs rm
    fi

